### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shun159** [shun159/fou#104]
- [ ] Use libofppacket to generate test packets
- [ ] Keep alive and disconnecting.
- [ ] Disconnect dapapath with not support for ofp_version=0x01
- [ ] Replace lagar with standard error logger.
- [ ] Improve pub/sub system.
- [ ] Improve fast counters.
- [ ] Rename modules from fou* to ofc* or ofs*.
- [ ] Fix openflow_controller module in order to use generic behaviors.
- [ ] E2E CI.
- [ ] Fix protocol modules in order to specify 124 byte user data in GENEVE TLV.
- [ ] Add perf module for testing
- [ ] clean up a code for convert ofproto record into map.
- [ ] Implement OVSDB/OpenFlow abstruction layer
- [ ] Fast C OpenFlow Parsers
